name: Daily Fragrance Scanner

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8am UTC
  workflow_dispatch:    # Allows manual button click

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION_STRING: ${{ secrets.TG_SESSION_STRING }}
        run: python scraper.py
      - uses: actions/upload-artifact@v4
        with:
          name: fragrance-prices
          path: fragrance_prices.xlsx
